### ISSUE TITLE
文件系统没有挂载吗

### ISSUE THREAD

**Issue by gt-sun** [zeromake/docker-debug#1]
debug 进去之后文件系统跟容器不一致

**Comment by zeromake** [comment]
@gt-sun target container filesystem `/` default mount on new container `/mnt/container`

**Comment by zeromake** [comment]
@gt-sun 
next version set on config file and command

**Comment by zeromake** [comment]
@gt-sun 

v0.2.1 release, target container filesystem `/` default mount on new container `/mnt/container`

config file: `~/.docker-debug/config.toml`, `mount_dir` is target container filesystem `/` default mount on new container dir.
`mount_dir` is `""` not mount target container filesystem.
