### ISSUE TITLE
brew install failed

### ISSUE THREAD

**Issue by jinwik** [zeromake/docker-debug#13]
brew install docker-debug
==> Downloading https://github.com/zeromake/docker-debug/releases/download/v0.7.4/docker-debug-darwin-amd64
Error: docker-debug: SHA256 mismatch
Expected: d515939ccdde206461bdde33256367fa738386d85548d748fffbeef608c03828
  Actual: 0bb821fac268b1bf30bf6cb217a2bea103f3079ff634a3db1fe62c5dc4b899ef

**Comment by zeromake** [comment]
@jinwik 
Fixed sha256sum

**Comment by jinwik** [comment]
thx
