### ISSUE TITLE
无法调试

### ISSUE THREAD

**Issue by hexiaoen** [zeromake/docker-debug#14]
ERRO[0005] Error: read unix ->/Users/nothing/.docker/run/docker.sock: i/o timeout

**Comment by zeromake** [comment]
@hexiaoen 
是什么环境呢，可以强制指定一下正确的 host。
修改 ~/.docker-debug/config.toml 文件里的 default 的 host。
```toml
[config]
  [config.default]
    host = "unix:///var/run/docker.sock"
```

**Comment by zeromake** [comment]
话说 `/Users/nothing/.docker/run/docker.sock` 是哪来的，我这个工具没有内置这种 `unix://~/.docker/run/docker.sock` 的地址吧。

**Comment by hexiaoen** [comment]
我也不知道是哪里来的，我是mac，用brew 安装的。配置文件里面是unix:///var/run/docker.sock这个，我也没动过。所以就很奇怪。

**Comment by hexiaoen** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/25130920/179728628-b6c44096-5ba1-489a-8ff3-f5a1fe5d86bb.png">
这个路径下这个文件也存在，发现所有的容器都一样的无法，尝试了重启docker也不行。

**Comment by zeromake** [comment]
@hexiaoen 
看看 
```bash
ls -l /var/run/docker.sock
```

**Comment by hexiaoen** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/25130920/179733358-27ad0be4-d00d-4e61-a3c8-3ad9909d1061.png">

**Comment by zeromake** [comment]
@hexiaoen 
你自己的 docker 是能正常运行的是吗

**Comment by zeromake** [comment]
@hexiaoen 
我的黑苹果刚刚安装了
```bash
brew install homebrew/cask-versions/docker-edge
```
正常啊不过，sock 地址不一样
```bash
> ls -l /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  65  7 19 19:52 /var/run/docker.sock@ -> /Users/zero/Library/Containers/com.docker.docker/Data/docker.sock
```

**Comment by hexiaoen** [comment]
我的docker是可以用的，可能是环境的问题，但是确实不知道为什么会这样

**Comment by zeromake** [comment]
@hexiaoen 
更新到 `0.7.6`,增加了一个 `read_timeout`，我这边有一个 socket 读取超时，官方的 cli 是没有的。

```bash
brew upgrade zeromake/docker-debug/docker-debug 
```

参考默认是 `3000000000` 是 `3s` 试试改成 `600s` 看看。
~/.docker-debug/config.toml

``` toml
version = "0.7.6"
read_timeout = 600000000000
```

**Comment by hexiaoen** [comment]
升级了版本，然后改了一下配置文件，可以正常使用了，但是到了600s后，还是会报同样的错。是不是可以把read_timeout到很大，或者有没有-1表示不超时这种，会不会有什么影响？

**Comment by zeromake** [comment]
@hexiaoen 
我修改支持一下 <= 0 去支持不超时吧，只是用于检测容器存活罢了

**Comment by zeromake** [comment]
@hexiaoen 
已发布 0.7.7，修改 `read_timeout` 为 -1 即可支持不超时

**Comment by hexiaoen** [comment]
可以了，感谢

**Comment by zeromake** [comment]
@hexiaoen 
尝试使用 bash 写了一个，不过各种参数都不好去支持
[docker-debug.sh](https://raw.githubusercontent.com/zeromake/docker-debug/master/shell/docker-debug.sh)
代码超少：
```bash
#!/bin/bash

set -e
inspectInfo=$(docker inspect "$1")
containerId=$(echo "$inspectInfo" | grep "Id" | cut -d'"' -f 4)
mergedDir=$(echo "$inspectInfo" | grep "MergedDir" | cut -d'"' -f 4)
targetName="container:$containerId"
name=$(docker run --network $targetName --pid $targetName --stop-signal SIGKILL -v $mergedDir:/mnt/container --rm -it -d nicolaka/netshoot:latest /usr/bin/env sh)
args="${@:2}"
docker exec -it "$name" $args
docker stop "$name" > /dev/null &
```
