### ISSUE TITLE
是否可以提供webshell支持，如果只提供命令行，这个工具的意义不是特别大。如果我理解有问题，请指正我。

### ISSUE THREAD

**Issue by mingplan** [zeromake/docker-debug#2]

**Comment by zeromake** [comment]
@mingplan 

如果只是想远程操作有很多webshell挂到宿主机上就可以了，而且还带各种权限控制。
看到你的这个 issues 我也考虑了一下在这个里的实现方案，和 `aria2` 的方案类似，`docker-debug` 命令行启动一个http服务，然后做一个 `gitpage` 页来调用 `docker-debug`。
