### ISSUE TITLE
docker-debug containerID bash 运行几秒钟自动退出

### ISSUE THREAD

**Issue by mask-pp** [zeromake/docker-debug#22]
错误内容：
ERRO[0004] Error: read unix ->/xxx/.docker/run/docker.sock: i/o timeout

**Comment by zeromake** [comment]
是哪个镜像产生的呢？

**Comment by zeromake** [comment]
找了一下只有一个地方设置超时应该是写入超时设置，写成了读取超时导致出现问题，已经发布 0.7.8 版本（没有测试）
https://github.com/zeromake/docker-debug/compare/v0.7.7...v0.7.8#diff-9d87f99498d08f0cad4a5477afa03a13aed78b8b63571df6c86cc58e5c25eba3L162

**Comment by zeromake** [comment]
可以考虑改用超级精简的 shell 版本 [shell/docker-debug.sh](https://github.com/zeromake/docker-debug/blob/master/shell/docker-debug.sh) 来替代，这个应该也能满足大部分需求

**Comment by mask-pp** [comment]
我试一下，多谢多谢

**Comment by mask-pp** [comment]
这种问题解决了
