### ISSUE TITLE
container 清退 后，docker-debug 终端卡死且无法退出

### ISSUE THREAD

**Issue by mask-pp** [zeromake/docker-debug#24]

**Comment by zeromake** [comment]
@mask-pp 这个问题一直在，可以考虑先用 bash 的版本 https://github.com/zeromake/docker-debug/blob/master/shell/docker-debug.sh

**Comment by mask-pp** [comment]
> @mask-pp 这个问题一直在，可以考虑先用 bash 的版本 https://github.com/zeromake/docker-debug/blob/master/shell/docker-debug.sh

Ok， 了解 抽空 我帮忙看看

**Comment by mask-pp** [comment]
> @mask-pp 这个问题一直在，可以考虑先用 bash 的版本 https://github.com/zeromake/docker-debug/blob/master/shell/docker-debug.sh

@zeromake https://github.com/zeromake/docker-debug/pull/25 这个PR 解决了这个问题，并且简化了 root.go 逻辑

**Comment by zeromake** [comment]
@mask-pp 好的，我测试一下

**Comment by zeromake** [comment]
@mask-pp 没什么问题，不过我看 [docker-cli/exec.go](https://github.com/docker/cli/blob/master/cli/command/container/exec.go) 里确实没有找到有额外处理容器状态的情况，看了一下 [docker-cli/utils.go](https://github.com/docker/cli/blob/master/cli/command/container/utils.go) 看起来 1.30 以上有另一个api来等待，有空把这个搬过来

**Comment by mask-pp** [comment]
> @mask-pp 没什么问题，不过我看 [docker-cli/exec.go](https://github.com/docker/cli/blob/master/cli/command/container/exec.go) 里确实没有找到有额外处理容器状态的情况，看了一下 [docker-cli/utils.go](https://github.com/docker/cli/blob/master/cli/command/container/utils.go) 看起来 1.30 以上有另一个api来等待，有空把这个搬过来

可以， 我抽空看看
