### ISSUE TITLE
Version is too new 

### ISSUE THREAD

**Issue by MatteoGauthier** [zeromake/docker-debug#28]
Hey ! I got this error while testing your tool

```
ERRO[0000] Error: Error response from daemon: client version 1.46 is too new. Maximum supported API version is 1.45
```

**Comment by zeromake** [comment]
@MatteoGauthier 
https://github.com/zeromake/docker-debug#default-image
change version is 1.40

**Comment by MatteoGauthier** [comment]
Okay thanks, it's now working
