### ISSUE TITLE
Error: Error response from daemon: client version 1.46 is too new. Maximum supported API version is 1.41

### ISSUE THREAD

**Issue by hkui** [zeromake/docker-debug#29]
![image](https://github.com/user-attachments/assets/75c70721-8947-49f0-9411-ea7e0a95293a)

[root@master1 phpality]# docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:24 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

-----------------
[root@master1 phpality]# docker-debug info
Version:	0.7.9
Platform:	TravisLinux
Commit:		e897cf5
Time:		2024-08-20 07:29:32 +0000

怎么解决呀

**Comment by zeromake** [comment]
@hkui 
[v0.7.10](https://github.com/zeromake/docker-debug/releases/tag/v0.7.10) 改为默认使用 1.40,如果发现配置里用的 1.46 会默认改为 1.40
