### ISSUE TITLE
Some lib are missing in the go.mod

### ISSUE THREAD

**Issue by athoune** [zeromake/docker-debug#4]
* github.com/sirupsen/logrus
* github.com/blang/semver

**Comment by zeromake** [comment]
@athoune 
I see the `go.mod` is has `github.com/sirupsen/logrus` and `github.com/blang/semver`
[go.mod#L23](https://github.com/zeromake/docker-debug/blob/master/go.mod#L23)
[go.mod#L9](https://github.com/zeromake/docker-debug/blob/45f1b199cee145470d65f7c0147cb84203e4bb49/go.mod#L9)

**Comment by athoune** [comment]
I can't reproduce the error. My bad, sorry for the noise.
