### ISSUE TITLE
docker client版本太高了，请问哪个版本支持docker 18.09的

### ISSUE THREAD

**Issue by cg831344** [zeromake/docker-debug#9]
Error: Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39

**Comment by zeromake** [comment]
@cg831344 更新到 [v0.7.3](https://github.com/zeromake/docker-debug/releases/tag/0.7.3) 可以在配置文件中切换 docker client 的版本号。配置在 `~/.docker-debug/config.toml` 格式见 [README](https://github.com/zeromake/docker-debug/blob/master/README-zh-Hans.md#%E9%BB%98%E8%AE%A4%E9%95%9C%E5%83%8F)

**Comment by cg831344** [comment]
好的谢谢
